### ISSUE TITLE
Creates check with npm global packages is broken

### ISSUE THREAD

**Issue by alonisser** [moviedo/ansible-role-nvm#5]
If the package already exists but with another version then the one we specified it won't be installed (only checked for existing binary but not for version)

Options:
1. Remove this check, and try to reinstall in every run
2. Replace with another check? 

@moviedo What do you think?

**Comment by moviedo** [comment]
Looking into this behavior, will update code to fix this issue. It definitely seems like another check is need in order to determine if a package needs to be updated as opposed to installed.

**Comment by alonisser** [comment]
recreate scenario
Install npm@3.9 -g
on packages in the playbook specify npm@5.5.1
run the playbook and then check npm --version
- expected: 5.5.1
- actual: 3.9

**Comment by moviedo** [comment]
Since I last looked at this issue I think that handling global packages as a feature should be removed. I feel that this role should really only focus on installing NVM. 

As a side note, with the advent of npx, global packages are far and few as the [convention](https://nodejs.dev/npm-global-or-local-packages) for most node projects is to use npx. `npx vue-cli-service serve` or `npx create-react-app my-app`.

The only time I see the need for global package use is with **yarn**.

Let me know your thoughts.

**Comment by alonisser** [comment]
While this was opened long ago :) I do agree that global packages are probably a no go today
